### ISSUE TITLE
More Local Setup fails after latest changes

### ISSUE THREAD

**Issue by uri-99** [matter-labs/local-setup#18]
[+1](https://github.com/matter-labs/local-setup/issues/17)

I also have a problem with this tool after latest commit https://github.com/matter-labs/local-setup/commit/2605e172467f014121df51fed6006df25921c96a.
I will post it here, since it is a different problem.

I use this tool in a CI, and noticed it started failing today:

<img width="383" alt="image" src="https://github.com/matter-labs/local-setup/assets/43704209/f180a504-a03d-412f-95fe-8033fae59418">

I tried running locally (macOS, silicon chip) and the same error:
<img width="1280" alt="image" src="https://github.com/matter-labs/local-setup/assets/43704209/450561b9-ac95-4a51-8bc2-dbb5ca3f21b4">

I thought about checking out the [previous commit](https://github.com/matter-labs/local-setup/commit/f16f1843b5740ca8456432123badafa137daaa02) , since it has worked many times, but still there seems to be another problem when running it in both the CI and locally:

CI:
<img width="611" alt="image" src="https://github.com/matter-labs/local-setup/assets/43704209/c6a009f3-58d8-4de4-9b6f-df7e68af8397">

Same problem, when running locally:
<img width="762" alt="image" src="https://github.com/matter-labs/local-setup/assets/43704209/8f879a9a-c9f6-48ca-ac99-021aad7fd951">

I suspect this might be related to the updated Docker [matterlabs/local-node:latest2.0](https://hub.docker.com/layers/matterlabs/local-node/latest2.0/images/sha256-e2f20e45ed0e63ba9700da55f9f18ebf8b0a198b0cec40514e73d6867b65658f?context=explore) image.

**Comment by uri-99** [comment]
I suspect this might be related to the updated Docker [matterlabs/local-node:latest2.0](https://hub.docker.com/layers/matterlabs/local-node/latest2.0/images/sha256-e2f20e45ed0e63ba9700da55f9f18ebf8b0a198b0cec40514e73d6867b65658f?context=explore) image

**Comment by benceharomi** [comment]
[local-node image](https://hub.docker.com/r/matterlabs/local-node/tags) has been updated in the meantime. Are you still having this problem?
Please make sure that you use these images:
* [matterlabs/local-node:latest2.0](https://hub.docker.com/layers/matterlabs/local-node/latest2.0/images/sha256-7caf61fac152986915ff8d865a136f78b695a5ed3587883218fb2fd37fe67140)
* [postgres:14](https://hub.docker.com/layers/library/postgres/14/images/sha256-a28005f051c26406f8e718e411a1068462a297dae049cddb513194d36dd8f29f)
* [reth:v0.2.0-beta.2](https://github.com/paradigmxyz/reth/pkgs/container/reth/190594989?tag=v0.2.0-beta.2)
```
➜  ~ docker inspect --format='{{index .RepoDigests 0}}' matterlabs/local-node:latest2.0

matterlabs/local-node@sha256:7caf61fac152986915ff8d865a136f78b695a5ed3587883218fb2fd37fe67140
➜  ~ docker inspect --format='{{index .RepoDigests 0}}' postgres:14

postgres@sha256:d6850c40261fdc9a4fb33b9521d9d641c4a5dcb82145f7bcc32c9258f81e75a2
➜  ~ docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/paradigmxyz/reth:v0.2.0-beta.2

ghcr.io/paradigmxyz/reth@sha256:ce7f45d7fd54245b51d8b17935da801d87978d8eabec1d3cda6abf0d133373f8
```

**Comment by benceharomi** [comment]
I'm closing this, if you are having issues with the latest images, please open a new issue!
