### ISSUE TITLE
Rich wallets are not actually rich

### ISSUE THREAD

**Issue by mmv08** [matter-labs/local-setup#19]
I wanted to run the node for local hardhat testing, however I couldn't run any of tests because the rich accounts from [readme](https://github.com/matter-labs/local-setup/blob/main/rich-wallets.json) have 0 native token balance

```
curl --location 'localhost:3050' \
--header 'Content-Type: application/json' \
--data '{
    "id": 1,
    "jsonrpc": "2.0",
    "params": ["0x36615Cf349d7F6344891B1e7CA7C72883F5dc049", "latest"],
    "method": "eth_getBalance"
}'

{"jsonrpc":"2.0","result":"0x0","id":1}
```

log: [zksync-local.log](https://github.com/matter-labs/local-setup/files/15132179/zksync-local.log)

**Comment by benceharomi** [comment]
We just fixed the issue, rich accounts are rich again!
Please use [the latest image](https://hub.docker.com/layers/matterlabs/local-node/latest2.0/images/sha256-1ca19797ddc68806ad7fe7d007a898f6342548b98d53b12bf1e4b439dc80bcdb?context=explore): `docker compose pull` should do it.

```
➜  ~ docker inspect --format='{{index .RepoDigests 0}}' matterlabs/local-node:latest2.0
matterlabs/local-node@sha256:1ca19797ddc68806ad7fe7d007a898f6342548b98d53b12bf1e4b439dc80bcdb
```
